version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Training_Bank_Backend/Dockerfile
    ports:
      - "8080:8080"
  tests:
    build:
      context: .
      dockerfile: Training_Bank_Backend.Tests/Dockerfile
    depends_on:
      - backend